'use client';

import { useState, useEffect } from 'react';
import { useAccount } from '@/hooks/useAccount';
import { motion } from 'framer-motion';
import PageTransition from '@/components/ui/PageTransition';
import AnimatedButton from '@/components/ui/AnimatedButton';
import LoadingSpinner from '@/components/ui/LoadingSpinner';
import { fadeInUp, staggerContainer } from '@/lib/animations/variants';
import { Utensils, Zap, CheckCircle, Lightbulb, Heart, Apple, Salad, Soup, Sun as SunMedium, Leaf, Activity } from 'lucide-react';
import Link from 'next/link';

export default function MealPlansPage() {
  const { address } = useAccount();
  const [mealPlans, setMealPlans] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Mock data for now
    setMealPlans([
      {
        id: '1',
        name: 'Keto Kickstart Plan',
        description: 'A 7-day ketogenic meal plan designed for rapid metabolic adjustment.',
        isActive: true,
        meals: [
          { id: 'm1', type: 'breakfast', name: 'Scrambled Eggs with Avocado', calories: 400, protein: 25, completed: false },
          { id: 'm2', type: 'lunch', name: 'Grilled Salmon Salad', calories: 500, protein: 35, completed: false },
          { id: 'm3', type: 'dinner', name: 'Steak with Asparagus', calories: 600, protein: 45, completed: false },
        ],
      },
      {
        id: '2',
        name: 'Longevity Mediterranean Plan',
        description: 'Focuses on whole foods, healthy fats, and rich antioxidants for long-term health.',
        isActive: false,
        meals: [
          { id: 'm4', type: 'breakfast', name: 'Greek Yogurt with Berries', calories: 300, protein: 20, completed: false },
          { id: 'm5', type: 'lunch', name: 'Lentil Soup with Whole Grain Bread', calories: 450, protein: 18, completed: false },
          { id: 'm6', type: 'dinner', name: 'Baked Cod with Roasted Vegetables', calories: 550, protein: 30, completed: false },
        ],
      },
    ]);
    setLoading(false);
  }, [address]);

  const generateMealPlan = async () => {
    if (!address) return;
    // Simulate API call
    setLoading(true);
    setTimeout(() => {
      const newPlan = {
        id: (Math.random() * 1000).toFixed(0),
        name: 'AI Generated Plan ' + (mealPlans.length + 1),
        description: 'A custom meal plan generated by AI based on your latest health data.',
        isActive: false,
        meals: [
          { id: 'm7', type: 'breakfast', name: 'Oatmeal with Nuts', calories: 350, protein: 15, completed: false },
          { id: 'm8', type: 'lunch', name: 'Chicken and Quinoa Bowl', calories: 480, protein: 30, completed: false },
          { id: 'm9', type: 'dinner', name: 'Vegetable Stir-fry', calories: 400, protein: 12, completed: false },
        ],
      };
      setMealPlans((prev) => [...prev, newPlan]);
      setLoading(false);
      alert('New meal plan generated! (Mock) Earned 5 $TA (Mock)');
    }, 2000);
  };

  return (
    <PageTransition>
      <div className="page-container">
        <motion.div initial="initial" animate="animate" variants={fadeInUp} className="flex justify-between items-center page-header">
          <div>
            <h1 className="page-title">Personalized Meal Plans</h1>
            <p className="page-subtitle max-w-2xl">
              Optimize your nutrition with AI-generated meal plans tailored to your goals.
            </p>
          </div>
          <AnimatedButton onClick={generateMealPlan} icon={<Zap className="w-4 h-4" />}>
            Generate New Plan
          </AnimatedButton>
        </motion.div>

        {loading ? (
          <div className="flex justify-center items-center h-96">
            <LoadingSpinner text="Loading meal plans..." />
          </div>
        ) : mealPlans.length === 0 ? (
          <motion.div initial="hidden" animate="visible" variants={fadeInUp} className="glass-card text-center py-12">
            <Utensils className="w-16 h-16 text-text-tertiary mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-text-primary mb-2">No Meal Plans Yet</h2>
            <p className="text-text-secondary mb-6">
              Generate a personalized meal plan based on your health goals and dietary preferences.
            </p>
            <AnimatedButton onClick={generateMealPlan}>
              Create Your First Meal Plan
            </AnimatedButton>
          </motion.div>
        ) : (
          <motion.div className="space-y-6" variants={staggerContainer} initial="hidden" animate="visible">
            {mealPlans.map((plan) => (
              <motion.div key={plan.id} variants={fadeInUp} className="glass-card-hover p-6">
                <div className="flex justify-between items-start mb-4">
                  <div>
                    <h3 className="text-2xl font-bold text-text-primary mb-2">
                      {plan.name}
                    </h3>
                    {plan.description && (
                      <p className="text-text-secondary text-sm mt-2">{plan.description}</p>
                    )}
                  </div>
                  <span className={`px-3 py-1 rounded-full text-sm font-semibold border ${
                    plan.isActive
                      ? 'bg-semantic-success/10 text-semantic-success border-semantic-success/20'
                      : 'bg-bg-elevated text-text-secondary border-border-medium'
                  }`}>
                    {plan.isActive ? 'Active' : 'Inactive'}
                  </span>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">
                  {plan.meals?.map((meal: any) => (
                    <div
                      key={meal.id}
                      className="glass-card p-4"
                    >
                      <div className="font-semibold text-text-primary mb-2 flex items-center gap-2">
                        {meal.type === 'breakfast' && <SunMedium className="w-5 h-5 text-yellow-500" />}
                        {meal.type === 'lunch' && <Salad className="w-5 h-5 text-green-500" />}
                        {meal.type === 'dinner' && <Soup className="w-5 h-5 text-blue-500" />}
                        {meal.type.charAt(0).toUpperCase() + meal.type.slice(1)}
                      </div>
                      <p className="text-lg font-bold text-accent-primary mb-2">{meal.name}</p>
                      {meal.calories && (
                        <p className="text-sm text-text-secondary">
                          {meal.calories} cal
                          {meal.protein && ` • ${meal.protein}g protein`}
                        </p>
                      )}
                      {meal.completed && (
                        <p className="mt-2 text-semantic-success text-sm flex items-center gap-1">
                          <CheckCircle className="w-4 h-4" /> Completed
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </motion.div>
            ))}
          </motion.div>
        )}

        {/* Disease-Specific Guidance */}
        <motion.div className="glass-card p-6 mt-8" variants={fadeInUp}>
          <h2 className="text-xl font-bold text-text-primary mb-4 flex items-center gap-2">
            <Lightbulb className="w-6 h-6 text-accent-primary" /> Disease-Specific Guidance
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <motion.div variants={fadeInUp} className="glass-card-hover p-4">
              <div className="text-2xl mb-2 flex items-center gap-2 text-red-400"><Heart className="w-6 h-6" /></div>
              <h3 className="font-semibold text-text-primary mb-2">Cardiovascular Health</h3>
              <p className="text-sm text-text-secondary">
                Mediterranean diet, cholesterol management, blood pressure tracking.
              </p>
            </motion.div>
            <motion.div variants={fadeInUp} className="glass-card-hover p-4">
              <div className="text-2xl mb-2 flex items-center gap-2 text-green-400"><Apple className="w-6 h-6" /></div>
              <h3 className="font-semibold text-text-primary mb-2">Diabetes Management</h3>
              <p className="text-sm text-text-secondary">
                Low-carb meal plans, glycemic index tracking, blood sugar monitoring.
              </p>
            </motion.div>
            <motion.div variants={fadeInUp} className="glass-card-hover p-4">
              <div className="text-2xl mb-2 flex items-center gap-2 text-purple-400"><Leaf className="w-6 h-6" /></div>
              <h3 className="font-semibold text-text-primary mb-2">Gut Health Optimization</h3>
              <p className="text-sm text-text-secondary">
                Probiotic-rich foods, fiber focus, personalized dietary adjustments.
              </p>
            </motion.div>
            <motion.div variants={fadeInUp} className="glass-card-hover p-4">
              <div className="text-2xl mb-2 flex items-center gap-2 text-blue-400"><Activity className="w-6 h-6" /></div>
              <h3 className="font-semibold text-text-primary mb-2">Performance & Muscle Gain</h3>
              <p className="text-sm text-text-secondary">
                High-protein meal plans, macro tracking, workout nutrition strategies.
              </p>
            </motion.div>
          </div>
        </motion.div>
      </div>
    </PageTransition>
  );
}
